train:
  n_estimators: 100
  max_depth: 5
  random_state: 42
  test_size: 0.2
  target_col: "target"

paths:
  data: "data/iris_preprocessed.csv"
  model: "models/random_forest.pkl"
  metrics_train: "metrics/train_metrics.json"
  metrics_eval: "metrics/eval_metrics.json"
